### ISSUE TITLE
$self->mango undefined inside Mango::Database

### ISSUE THREAD

**Issue by jkramer** [oliwer/mango#2]
This code:

    my $m = Mango->new->db('abc')->collection('xyz');
    $m->insert(...)

Gives me this error:

    Can't call method "j" on an undefined value at .../perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Mango/Database.pm line 14.

However this:

    my $mango = Mango->new;
    my $m = $mango->db('abc')->collection('xyz');
    $m->insert(...)

works just fine.

**Comment by dotandimet** [comment]
Mango behaves like this to prevent memory leaks.
To work, a Mango instance needs to know about its Mango::Database objects, the Mango::Collection needs to know its Mango::Database, and a Mango::Database needs to know about both the Mango instance and the Mango::Collections its database holds. But Perl doesn't garbage-collect circular references, so the code takes care to [weaken()](https://metacpan.org/pod/Scalar::Util#weaken) each object's reference to its owning object, so that everything gets cleaned up when you're done with it.
The drawback is that you need to hold onto your Mango instance to prevent it from being `DESTROY()`-ed before your collection (which only holds a weakened reference through its weakened reference to the db()) can use it.

**Comment by oliwer** [comment]
It is just like @dotandimet said. That is why you are advised to create a helper subroutine like this:

    sub mango { state $m = Mango->new("mongodb://...") }

and always access to your database through this helper.

Note that this behavior will probably change in the future when support for replica set monitoring has been implemented.
